//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public int WishListId { get; set; }
        public string UserId { get; set; }
        public int BookId { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Book Book { get; set; }
    }
}
